### ISSUE TITLE
Mnist dataset test error 

### ISSUE THREAD

**Issue by Mengke-Yuan** [WHULuoJiaTeam/luojianet#1]
Compling with cuda 11.1 and cudnn 8 on unbuntu 18.04, run 
```
example/quick_start.py
```
got error of 
```
RuntimeError: Unexpected error. Invalid mnist file, the image number of /home/work/luojia/luojianet/datasets/MNIST_Data/train/train-images-idx3-ubyte should be 2051, but got 1010792557
Line of code : 119
File         : /home/work/luojia/luojianet/luojianet_ms/ccsrc/minddata/dataset/engine/datasetops/source/mnist_op.cc
```
It looks like dataset loading problem.

**Comment by MiZhangWhuer** [comment]
> Compling with cuda 11.1 and cudnn 8 on unbuntu 18.04, run
> 
> ```
> example/quick_start.py
> ```
> 
> got error of
> 
> ```
> RuntimeError: Unexpected error. Invalid mnist file, the image number of /home/work/luojia/luojianet/datasets/MNIST_Data/train/train-images-idx3-ubyte should be 2051, but got 1010792557
> Line of code : 119
> File         : /home/work/luojia/luojianet/luojianet_ms/ccsrc/minddata/dataset/engine/datasetops/source/mnist_op.cc
> ```
> 
> It looks like dataset loading problem.

The quick start example has been updated. Please try it out. https://github.com/WHULuoJiaTeam/luojianet/blob/master/examples/tutorial/quick_start.py

**Comment by ymk11235** [comment]
Thx, It worked!

**Comment by Mengke-Yuan** [comment]
Thx, It worked.

**Comment by DeadPoetSpoon** [comment]
提醒一下，文档中代码未更新
https://whu.obs.cn-central-221.ovaijisuan.com/instruction/quick_start.html
