### ISSUE TITLE
是否有适配ubuntu 22.04 & cuda11.2的安装包呢?

### ISSUE THREAD

**Issue by DewenLi** [WHULuoJiaTeam/luojianet#10]
如题

**Comment by ADHuan** [comment]
这个问题交由 @Limanman507 同学来跟进

**Comment by Limanman507** [comment]
您好，可以参考我们官网的教程（http://58.48.42.237:5200/luojiaNet/install/docs）尝试使用源码编译的方式安装。同时我们也会推进该版本的安装包。

**Comment by Limanman507** [comment]
您好，可以参考我们(官网的教程)[http://58.48.42.237:5200/luojiaNet/install/docs]尝试使用源码编译的方式安装。同时我们也会推进该版本的安装包。

**Comment by Limanman507** [comment]
您好，可以参考我们[官网的教程](http://58.48.42.237:5200/luojiaNet/install/docs)尝试使用源码编译的方式安装。同时我们也会推进该版本的安装包。

**Comment by DewenLi** [comment]
好的，多谢！
