### ISSUE TITLE
luojianet针对大幅面遥感影像解译的模块，具体怎么使用的

### ISSUE THREAD

**Issue by yangeri** [WHULuoJiaTeam/luojianet#12]
luojianet团队您好：
       有幸接触到luojianet这样一个遥感专用机器学习框架，我对其中的大幅面遥感影像解译比较感兴趣。查阅了相关资料，还是不太清楚在使用时，具体应该怎么做。具体问题是：
      在模型训练的时候，是将整幅影像扔进去训练吗，不需要裁切成小图了是吗？
      扔进去之后，相较于常规的深度学习框架中的模型训练，会有哪些不一样的处理呢？
      希望您能帮我解答疑惑

**Comment by LuoJiaTeam** [comment]
> 
您好！谢谢您对luojianet团队的关注。关于大幅面处理的相关方法，在项目主页做了使用方法的文档更新，请您查阅：
http://58.48.42.237/luojiaNet/tutorial/experts
