### ISSUE TITLE
关于大幅面影像处理的问题

### ISSUE THREAD

**Issue by WBS-123** [WHULuoJiaTeam/luojianet#13]
在官方教程中http://58.48.42.237/luojiaNet/tutorial/experts有提到大幅面处理的相关方法。
请问大幅面影像四叉树处理和大幅面影像算子分解是什么关系呢？
在代码中我只看到了QuadSearch_GID的整体流程，没有看到大幅面影像算子分解的具体代码。所以大幅面影像算子分解是四叉树处理中的一个部分吗？还是说暂时还没有大幅面影像算子分解的具体代码（教程中只有代码片段，不能直接运行）

**Comment by MiZhangWhuer** [comment]
> 

1. QuardSearch_GID是大幅面影像采用四叉树编码方式进行空间上下文关联处理的一种方法
2. 大幅面影像的算子分解是另一种方式，示例中只提供了主要的处理代码片段。完整的处理实例，将在下一个版本中更新。
3. 在LuoJiaNet官网注册后，可以新建大幅面处理任务，以GID数据为例，上传影像，预先体验大幅面直接处理效果。
