### ISSUE TITLE
源码编译遇到的错误

### ISSUE THREAD

**Issue by virtuozo007** [WHULuoJiaTeam/luojianet#15]
按照官方教程一步步来的，1.0.6和master版本都试过了，都是同样的错误，到下面这一步报错，貌似跟openmpi有关

......
......
checking for netinet/tcp.h... yes
checking for struct sockaddr_in... yes
checking if --with-cuda is set... not set (--with-cuda=)
./configure: line 13028: syntax error near unexpected token `)'
./configure: line 13028: `    )'
CMake Error at cmake/utils.cmake:179 (message):
  error! when ./configure;CXXFLAGS=-D_FORTIFY_SOURCE=2
  -O2;--prefix=/home/rs/Codes/luojianet/build/luojianet_ms/.mslib/ompi_4.0.3_653b828d1fcd585d80aa35947b9dfeae
  in /home/rs/Codes/luojianet/build/luojianet_ms/_deps/ompi-src
Call Stack (most recent call first):
  cmake/utils.cmake:393 (__exec_cmd)
  cmake/external_libs/ompi.cmake:10 (luojianet_ms_add_pkg)
  cmake/mind_expression.cmake:43 (include)
  CMakeLists.txt:56 (include)

-- Configuring incomplete, errors occurred!
See also "/home/rs/Codes/luojianet/build/luojianet_ms/CMakeFiles/CMakeOutput.log".
See also "/home/rs/Codes/luojianet/build/luojianet_ms/CMakeFiles/CMakeError.log".

**Comment by MiZhangWhuer** [comment]
> 按照官方教程一步步来的，1.0.6和master版本都试过了，都是同样的错误，到下面这一步报错，貌似跟openmpi有关
> 
> ...... ...... checking for netinet/tcp.h... yes checking for struct sockaddr_in... yes checking if --with-cuda is set... not set (--with-cuda=) ./configure: line 13028: syntax error near unexpected token `)' ./configure: line 13028: ` )' CMake Error at cmake/utils.cmake:179 (message): error! when ./configure;CXXFLAGS=-D_FORTIFY_SOURCE=2 -O2;--prefix=/home/rs/Codes/luojianet/build/luojianet_ms/.mslib/ompi_4.0.3_653b828d1fcd585d80aa35947b9dfeae in /home/rs/Codes/luojianet/build/luojianet_ms/_deps/ompi-src Call Stack (most recent call first): cmake/utils.cmake:393 (__exec_cmd) cmake/external_libs/ompi.cmake:10 (luojianet_ms_add_pkg) cmake/mind_expression.cmake:43 (include) CMakeLists.txt:56 (include)
> 
> -- Configuring incomplete, errors occurred! See also "/home/rs/Codes/luojianet/build/luojianet_ms/CMakeFiles/CMakeOutput.log". See also "/home/rs/Codes/luojianet/build/luojianet_ms/CMakeFiles/CMakeError.log".

能提供具体的运行环境吗？采用的系统，linux环境，cuda版本，gcc版本等。
从报错的情况看，可能是openmpi下载过程中断，历史的cmake缓存文件没有清理造成的。
