### ISSUE TITLE
LuojiaNET如何处理大画幅遥感图片

### ISSUE THREAD

**Issue by MemoryCrash** [WHULuoJiaTeam/luojianet#2]
LuojiaNET团队您好

我从龚健雅院士的《龚健雅院士：遥感大数据与智能解译》报告初次了解到LuojiaNET框架。LuojiaNET针对大画幅遥感图像整体载入进行训练和推理做了框架层面优化。具介绍包括全局和局部影像关联、算子并行两种策略。现在我对模型如何进行大画幅训练和推理依然有不少问题，希望LuojiaNET团队可以给与解答。

* 大画幅遥感图像训练中利用到框架提供的大画幅加载功能，可否提供使用样例作为参考。
* 全局和局部影像关联策略是否只在模型加载大画幅图像时生效，不参与隐藏层大画幅处理。
* 算子并行策略是否是针对特征自动进行分割，类似数据并行。只是一般数据并行为分割Batch，而这里是对特征进行分割。
* 全局和局部影响管理、算子并行策略分别在源代码哪些目录实现。

感激回答。

**Comment by LuoJiaTeam** [comment]
> 

关于大幅面处理的相关方法，在项目主页做了使用方法的文档更新，请您查阅：
http://58.48.42.237/luojiaNet/tutorial/experts

**Comment by MemoryCrash** [comment]
谢谢：）
