### ISSUE TITLE
如何在Ascend710训练服务器安装LuojiaNET

### ISSUE THREAD

**Issue by MemoryCrash** [WHULuoJiaTeam/luojianet#3]
LuojiaNET团队您好

查看[官网安装](https://whu.obs.cn-central-221.ovaijisuan.com/instruction/install/luojianet_ms_gpu_install_pip.html)信息，发现仅提供x86 cpu以及gpu环境whl安装文件。请问如何在华为Ascend训练服务器安装LuojiaNET。

感激回答。

**Comment by LuoJiaTeam** [comment]
> LuojiaNET团队您好
> 
> 查看[官网安装](https://whu.obs.cn-central-221.ovaijisuan.com/instruction/install/luojianet_ms_gpu_install_pip.html)信息，发现仅提供x86 cpu以及gpu环境whl安装文件。请问如何在华为Ascend训练服务器安装LuojiaNET。
> 
> 感激回答。

NPU服务器下需要采用源码编译方式，编译方法与GPU源码编译方式类似（https://whu.obs.cn-central-221.ovaijisuan.com/instruction/install/luojianet_ms_linux_gpu_install_src.html )：
1. 编译NPU版本的GDAL
    bash build_gdal_npu.sh
3. 编译NPU版本的LuoJiaNET
    bash build_npu.sh -e ascend -j 4
3. 验证是否安装成功：
    python -c "import luojianet_ms;luojianet_ms.run_check()"

注意，目前在武汉人工智能计算中心Ascend 910服务器上已成功编译，并部署至华为云平台。如果有华为云账户，可直接登录，选择LuoJiaNET镜像服务。

**Comment by MemoryCrash** [comment]
感谢解答：）

**Comment by LuoJiaTeam** [comment]
> 感谢解答：）

感谢您反馈的宝贵意见：
另一个关于大幅面遥感影像处理的问题，我们正在完善相关文档。其核心包括：
1）四叉树索引构建（参见：https://github.com/WHULuoJiaTeam/luojianet/tree/master/luojianet_ms/ccsrc/quad_slice_patches ）
2）大幅面算子分解与编译优化（参见：https://github.com/WHULuoJiaTeam/luojianet/blob/d0ea05afb9d687a7cf7f100f39f2ee6a3c19d1f9/luojianet_ms/ccsrc/minddata/dataset/kernels/image/slice_patches_op.cc
https://github.com/WHULuoJiaTeam/luojianet/blob/master/luojianet_ms/ccsrc/frontend/parallel/ops_info/conv2d_info.cc ）
3）同时也有基于TVM的简化版本大幅面处理，参见：https://gitlab.com/whuluojiateam/luojianet/-/tree/OpDecomposition

更详细的教程和上层Python接口调用方法，我们整理后将在另一个issue下面作详细回复。

**Comment by MemoryCrash** [comment]
再次感谢 LuoJiaTeam 及时、专业的回答。期望 LuojiaNet 越做越好，成为遥感领域领先的AI框架。
