### ISSUE TITLE
I had this problem compiling GDAL when using Windows

### ISSUE THREAD

**Issue by Whu-gaozhao** [WHULuoJiaTeam/luojianet#6]
![屏幕截图 2022-07-01 101335](https://user-images.githubusercontent.com/92943212/176809935-4da4fe81-c47f-4091-8561-594515e00d0e.png)

**Comment by LuoJiaTeam** [comment]
> ![屏幕截图 2022-07-01 101335](https://user-images.githubusercontent.com/92943212/176809935-4da4fe81-c47f-4091-8561-594515e00d0e.png)

Re-run with MinGW-w64 environment！
