### ISSUE TITLE
luojianet并行训练效率提升问题

### ISSUE THREAD

**Issue by yangeri** [WHULuoJiaTeam/luojianet#9]
luojianet团队你们好!
在学习luojianet过程中，我们对分布式并行训练比较感兴趣。我们尝试了在单机多GPU环境下进行遥感影像语义分割的分布式并行训练，使用的模型是UNET语义分割模型。并且进行了一组对比实验，即不使用并行模式，直接在单GPU环境下进行训练。结果发现这两种训练方式耗时相差无几，不知道是什么原因，是因为多卡之间通信也有耗时吗？

还有，luojianet提供的这种并行训练它支持多机多GPU模式吗？

此外，当前Pytorch框架下也配备有分布式并行训练库，不知道在效率，精度方面，luojianet并行与Pytorch并行相比有什么区别。

**Comment by LuoJiaTeam** [comment]
> luojianet团队你们好! 在学习luojianet过程中，我们对分布式并行训练比较感兴趣。我们尝试了在单机多GPU环境下进行遥感影像语义分割的分布式并行训练，使用的模型是UNET语义分割模型。并且进行了一组对比实验，即不使用并行模式，直接在单GPU环境下进行训练。结果发现这两种训练方式耗时相差无几，不知道是什么原因，是因为多卡之间通信也有耗时吗？
> 
> 还有，luojianet提供的这种并行训练它支持多机多GPU模式吗？
> 
> 此外，当前Pytorch框架下也配备有分布式并行训练库，不知道在效率，精度方面，luojianet并行与Pytorch并行相比有什么区别。

非常感谢您使用LuoJiaNet，LuoJiaNet可支持单机单卡/多卡、多机多卡集群。
目前我们提供三种并行模式：数据并行、模型自动/半自动并行、混合并行；其中，自动并行方面，近期支持了sharding propagation方法，同时支持了DP方法与Double Recrusive方法，见目录：https://github.com/WHULuoJiaTeam/luojianet/blob/master/luojianet_ms/ccsrc/frontend/parallel/auto_parallel/rec_core

您提到的训练耗时问题，可能的原因是：1）数据加载方面耗时，请检查各种数据变换方式；2）模型方面耗时，请检查是否实际在GPU端运行开启了NCCL。

PyTorch默认采用的是数据并行模式，不能有效解决大幅面遥感影像处理问题，更详细的文档介绍和效率对比，正在准备中，将与论文同步发布。
